.\"                                      Hey, EMACS: -*- nroff -*-
.TH GNOMECATALOG 1 "September 27, 2007"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
gnomecatalog \- Cd cataloguing
.SH SYNOPSIS
.B gnomecatalog
.SH DESCRIPTION
This manual page documents briefly \fBgnomecatalog\fP.
Cataloging software for CDs and DVDs.
Catalog your dvds/cds and files in your hard disk.

You can find easily your files stored in your cds and dvds.
You can search in all metadata of the files, exif, id3tags, etc.
The files, disks and catalog can be commented and can annotate
if you borrow a disk to someone.

You can export your file list to send to your friends.

It can import data from other catalog software to your database.

The program has been developed in python-gtk uses sqlite3 for store the data.
.PP
\fBgnomecatalog\fP is a catalog software
.SH AUTHOR
This manual page was written by Jose Sanchez Moreno <jose@o2w.es>, for the
Debian GNU/Linux system (but may be used by others).
